branch-defaults:
  master:
    environment: stage
    group_suffix: null
global:
  application_name: helm
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application

