# Generated by Django 2.2.6 on 2019-10-03 18:42

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book_slug', models.SlugField(max_length=150, unique=True)),
                ('primary_author_first_name', models.CharField(
                    blank=True, max_length=100, verbose_name='Author First')),
                ('primary_author_last_name', models.CharField(
                    blank=True, max_length=100, verbose_name='Author Last')),
                ('pub_date', models.DateField(blank=True,
                                              null=True,
                                              verbose_name='Book Pub Date')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iso2', models.CharField(blank=True, max_length=50)),
                ('iso3', models.CharField(blank=True, max_length=50)),
                ('phone_code', models.CharField(blank=True, max_length=100)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universitie',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('web_page', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='primary_data.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject_slug', models.SlugField(
                                                max_length=150,
                                                unique=True)),
                ('code', models.CharField(max_length=250)),
                ('book', models.ManyToManyField(blank=True,
                                                to='primary_data.Book')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='primary_data.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Citie',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('country', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='primary_data.Country')),
                ('state', smart_selects.db_fields.ChainedForeignKey(
                                blank=True,
                                chained_field='country',
                                chained_model_field='country',
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                to='primary_data.State')),
            ],
        ),
    ]
