# Generated by Django 2.2 on 2020-01-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_auto_20200119_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineeringexamapplication',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='engineeringexamapplication',
            name='stream',
        ),
        migrations.CreateModel(
            name='EngineeringExamApplicationSubjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.EngineeringExamApplication')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='engineering.EngineeringSemester')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='engineering.EngineeringStream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='engineering.EngineeringSubject')),
            ],
        ),
    ]
