# Generated by Django 2.2 on 2020-01-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_auto_20200126_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringexamapplicationsubjectuser',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='engineering.EngineeringSemester'),
        ),
    ]
