# Generated by Django 2.2 on 2020-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_auto_20200127_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeringexamapplication',
            name='exam_type',
            field=models.CharField(choices=[('R', 'Reguler'), ('K', 'KT')], max_length=1),
        ),
    ]
